version: '3.8'

services:
  ocr-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ocr-api:latest
    container_name: ocr-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MAX_CONCURRENT_REQUESTS=20
      - WORKERS=${WORKERS:-4}
      - DEVICE=${DEVICE:-cpu}
      - PYTHONUNBUFFERED=1
    volumes:
      # 持久化模型檔案
      - ./best_lightweight_crnn_model.pth:/app/best_lightweight_crnn_model.pth:ro
      # 可選：持久化日誌
      - ./logs:/app/logs
    networks:
      - ocr-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.ocr.description=OCR API Service"
      - "com.ocr.version=2.0"
      - "com.ocr.accuracy=99.38%"

  # 可選：Nginx 反向代理（用於負載均衡）
  nginx:
    image: nginx:alpine
    container_name: ocr-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ocr-api
    networks:
      - ocr-network
    profiles:
      - production

  # 可選：監控服務
  prometheus:
    image: prom/prometheus:latest
    container_name: ocr-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - ocr-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: ocr-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - ocr-network
    profiles:
      - monitoring

networks:
  ocr-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: